title: TheCommandCat's Portfolio
description: "A gateway to my portfolio and services I develop and host."
url: "https://bhrtkhvji.github.io"

theme: minima

markdown: kramdown

author:
  name: TheCommandCat
  email: bhrtkhvji@example.com

social_links:
  github: "https://github.com/thecommandcat"
  instagram: "https://www.instagram.com/nir_chen2024/"

theme_settings:
  footer_text: "Made with ❤️ by TheCommandCat"
  accent_color: "#2c3e50"
  background_color: "#f4f4f4"
  button_color: "#3498db"
  link_color: "#2980b9"